### ISSUE TITLE
Cannot execute performance.py

### ISSUE THREAD

**Issue by RCoeurjoly** [DTJF/libpruio#2]
When I try to execute performance.py I get the following:

> python performance.py 
> Traceback (most recent call last):
>   File "performance.py", line 32, in <module>
>     from libpruio import *
>   File "/home/debian/examples/libpruio/__init__.py", line 1, in <module>
>     from pruio import *
>   File "/home/debian/examples/libpruio/pruio.py", line 877
>     try: PruReady = WHILE .DRam[1] : .WaitCycles += 1 : WEND
>                                    ^
> SyntaxError: invalid syntax
> 

I have installed all the dependencies mentioned in the documentation.

**Comment by DTJF** [comment]
Some FreeBASIC code found its way to the Python source. It's already fixed for the next version. The following link describes how you can help yourself:

https://groups.google.com/d/msg/beagleboard/z6Pr8ujQReQ/vCpC4e3oAgAJ
