### ISSUE TITLE
https://users.freebasic-portal.de/tjf/Projekte/libpruio/doc/html/ChaPreparation.html instructions broken

### ISSUE THREAD

**Issue by RobertPHeller** [DTJF/libpruio#3]
apt update is throwing a warning and is disabling the http://beagle.tuks.nl/debian repository, making it impossible to to use the repository:

W: GPG error: http://beagle.tuks.nl/debian jessie/ Release: Detached signature file '/var/lib/apt/lists/partial/beagle.tuks.nl_debian_jessie_Release.gpg' is in unsupported binary format

This is on a BeagleBone with a up-to-date image (running Debian 10 -- Buster).

apt  version:  1.8.2.2

**Comment by DTJF** [comment]
Hello Robert,

Thanks for reporting!

Unfortunately my computer is broken. I've to buy and set up a new one,
so I cannot help in short term.

I forwarded your report to the owner of the PPA (hello Arend!). Perhaps
he can fix the GPG file issue.

But note: since the current dabian ships with a new version of libtinfo
and the PPA binary is complied agains the old version from the Jessie
relaese, you'll get in to a dependency problem anyway.

So if you don't want to downgrade to Jessie, it's best to help yourself
by compiling from source.

Regards

Am 16.03.21 um 22:15 schrieb Robert Heller:
> apt update is throwing a warning and is disabling the http://beagle.tuks.nl/debian repository, making it impossible to to use the repository:
>
> W: GPG error: http://beagle.tuks.nl/debian jessie/ Release: Detached signature file '/var/lib/apt/lists/partial/beagle.tuks.nl_debian_jessie_Release.gpg' is in unsupported binary format
>
> This is on a BeagleBone with a up-to-date image (running Debian 10 -- Buster).
>
> apt  version:  1.8.2.2
>
>

**Comment by RobertPHeller** [comment]
At Wed, 17 Mar 2021 02:53:03 -0700 DTJF/libpruio ***@***.***> wrote:

> 
> Hello Robert,
> 
> Thanks for reporting!
> 
> Unfortunately my computer is broken. I've to buy and set up a new one,
> so I cannot help in short term.
> 
> I forwarded your report to the owner of the PPA (hello Arend!). Perhaps
> he can fix the GPG file issue.
> 
> But note: since the current dabian ships with a new version of libtinfo
> and the PPA binary is complied agains the old version from the Jessie
> relaese, you'll get in to a dependency problem anyway.
> 
> So if you don't want to downgrade to Jessie, it's best to help yourself
> by compiling from source.

Can't do that -- cmake fails -- it dosen't find the FreeBasic compiler.  I 
ended up downloading the .debs and installing with dpkg.

> 
> Regards
> 
> Am 16.03.21 um 22:15 schrieb Robert Heller:
> > apt update is throwing a warning and is disabling the http://beagle.tuks.nl/debian repository, making it impossible to to use the repository:
> >
> > W: GPG error: http://beagle.tuks.nl/debian jessie/ Release: Detached signature file '/var/lib/apt/lists/partial/beagle.tuks.nl_debian_jessie_Release.gpg' is in unsupported binary format
> >
> > This is on a BeagleBone with a up-to-date image (running Debian 10 -- Buster).
> >
> > apt  version:  1.8.2.2
> >
> >
> 
> 
> 

-- 
Robert Heller             -- Cell: 413-658-7953 GV: 978-633-5364
Deepwoods Software        -- Custom Software Services
http://www.deepsoft.com/  -- Linux Administration Services
***@***.***       -- Webhosting Services
